name: gcsl
channels:
- kne  # for pybox2d
- pytorch
- anaconda  # for mkl
dependencies:
  - flask
  - mkl
  - numpy
  - path.py
  - pybox2d
  - python
  - python-dateutil
  - scipy
  - patchelf
  - scikit-learn
  - mpi4py
  - pip:
    - wheel
    - cloudpickle
    - cached-property
    - plotly
    - gym[all]
    - gitpython
    - gtimer
    - pygame
    - tqdm
    # More optional ones:
    - catkin_pkg
    - ipdb
    - rospkg
    # mujoco-py<2.1,>
    - mujoco_py==1.50.1.56
    - scikit-video
    - opencv-python
    - box2d-py
